-- Hyprland config (Lua). hyprlang/.conf is deprecated since 0.55.
-- Structure follows the 0.56 example at /usr/share/hypr/hyprland.lua,
-- with personal settings replayed on top of it.
--
-- Types/autocomplete: point your Lua LSP at /usr/share/hypr/stubs/hl.meta.lua


------------------
---- MONITORS ----
------------------

hl.monitor({
    output   = "DP-3",
    mode     = "3440x1440@99.99Hz",
    position = "auto",
    scale    = 1,
})


---------------------
---- MY PROGRAMS ----
---------------------

local terminal    = "ghostty"
local browser     = "flatpak run app.zen_browser.zen"
local fileManager = "thunar"
local menu        = "rofi"


-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- NVIDIA: upstream now recommends only these two, plus NVD_BACKEND for VA-API.
-- GBM_BACKEND and XDG_SESSION_TYPE were dropped from the recommended set;
-- WLR_* vars are dead entirely (wlroots -> aquamarine since 0.42).
hl.env("LIBVA_DRIVER_NAME", "nvidia")
hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
hl.env("NVD_BACKEND", "direct")

hl.env("XCURSOR_SIZE", "24")
hl.env("XCURSOR_THEME", "macOS-BigSur")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_THEME", "macOS-BigSur")
hl.env("GTK_THEME", "rose-pine-gtk")


-------------------
---- AUTOSTART ----
-------------------

hl.on("hyprland.start", function()
    hl.exec_cmd("~/.config/hypr/scripts/apply-gtk-theme.sh")
    hl.exec_cmd("waybar")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("wl-paste --type text --watch cliphist store") -- text only
    hl.exec_cmd(terminal)
    hl.exec_cmd("~/.config/hypr/scripts/apply-desktop-experience.sh")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("swayosd-server") -- on-screen display for volume/mute
    hl.exec_cmd("hyprsunset")     -- night-light, profiles in hyprsunset.conf
end)


-----------------------
---- LOOK AND FEEL ----
-----------------------

hl.config({
    general = {
        gaps_in  = 10,
        gaps_out = 20,

        border_size = 2,

        resize_on_border = false,
        allow_tearing    = false,

        layout = "master",
    },

    decoration = {
        rounding       = 10,
        rounding_power = 2.0,

        active_opacity     = 1.0,
        inactive_opacity   = 0.9,
        fullscreen_opacity = 1.0,

        dim_inactive = true,
        dim_strength = 0.2,

        blur = {
            enabled  = true,
            size     = 5,
            passes   = 2,
            vibrancy = 0.282,
        },
    },

    animations = {
        enabled = true,
    },

    dwindle = {
        preserve_split = true,
    },

    master = {
        new_status = "slave",
    },

    misc = {
        force_default_wallpaper = 0,
        disable_hyprland_logo   = true,
    },

    ecosystem = {
        no_update_news  = true,
        no_donation_nag = true,
    },
})

-- Colors are generated by wallust into colors.lua on each wallpaper change.
-- Guarded: a missing/short-lived file must not take down the whole config.
pcall(function()
    dofile(os.getenv("HOME") .. "/.config/hypr/colors.lua")
end)


--------------------
---- ANIMATIONS ----
--------------------

hl.curve("spring", { type = "bezier", points = { { 0.12, 0.88 }, { 0.24, 1.12 } } })

hl.animation({ leaf = "windows",          enabled = true, speed = 2, bezier = "spring" })
hl.animation({ leaf = "windowsOut",       enabled = true, speed = 2, bezier = "default", style = "popin 80%" })
hl.animation({ leaf = "border",           enabled = true, speed = 8, bezier = "default" })
hl.animation({ leaf = "borderangle",      enabled = true, speed = 6, bezier = "default" })
hl.animation({ leaf = "fade",             enabled = true, speed = 4, bezier = "default" })
hl.animation({ leaf = "workspaces",       enabled = true, speed = 2, bezier = "default" })
hl.animation({ leaf = "specialWorkspace", enabled = true, speed = 2, bezier = "default", style = "fade" })


---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout  = "us",
        kb_variant = "",
        kb_model   = "",
        kb_options = "",
        kb_rules   = "",

        sensitivity  = 0, -- -1.0 - 1.0, 0 means no modification.
        accel_profile = "flat",

        repeat_delay = 200,
        repeat_rate  = 60,

        touchpad = {
            natural_scroll = false,
        },
    },
})

-- Per-device sensitivity. The old devices.conf targeted "logitech-usb-receiver-1/-2",
-- which no longer exist, so it had silently been a no-op -- left commented so the
-- current (unmodified) feel is preserved. Uncomment for whichever is your daily mouse;
-- check live names with: hyprctl devices
--
-- hl.device({ name = "logitech-pro-x-1",           sensitivity = -0.4 })
-- hl.device({ name = "machina-machina-orbit-mouse", sensitivity = -0.4 })


---------------------
---- KEYBINDINGS ----
---------------------

local meta      = "SUPER"
local navMod    = "SUPER + CTRL"
local launchMod = "CTRL + ALT"
-- NB: these were Shift_L&Alt_L / Control_L&Shift_L&Alt_L in the old hyprlang
-- config, but that never actually bound side-specific keys -- hyprlang
-- substring-matched the uppercased string, so they resolved to plain
-- SHIFT+ALT and CTRL+SHIFT+ALT. Lua parses *_L as keysyms instead, which
-- silently drops them from the modmask, so spell the modifiers out.
local moveMod   = "SHIFT + ALT"
local meh       = "CTRL + SHIFT + ALT"

hl.bind(meta .. " + Return", hl.dsp.exec_cmd(terminal))
hl.bind(meta .. " + Q", hl.dsp.window.close())
hl.bind(meta .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(meta .. " + B", hl.dsp.exec_cmd(browser))
hl.bind(navMod .. " + R", hl.dsp.exec_cmd("~/.config/hypr/scripts/restart-waybar.sh"))
hl.bind(meta .. " + SHIFT + V", hl.dsp.exec_cmd("cliphist list | " .. menu .. " -dmenu | cliphist decode | wl-copy"))
hl.bind(meh .. " + Escape", hl.dsp.exec_cmd("pkill " .. menu .. " || " .. menu .. " -show combi"))
hl.bind(meh .. " + Q", hl.dsp.exec_cmd(menu .. " -show p -modi p:rofi-power-menu"))

-- macOS-style clipboard: Super+C/V/X = copy/paste/cut (Ctrl+Shift+* inside terminals).
-- Add more (e.g. select-all on A) by extending mac-clipboard.sh.
hl.bind(meta .. " + C", hl.dsp.exec_cmd("~/.config/hypr/scripts/mac-clipboard.sh copy"))
hl.bind(meta .. " + V", hl.dsp.exec_cmd("~/.config/hypr/scripts/mac-clipboard.sh paste"))
hl.bind(meta .. " + X", hl.dsp.exec_cmd("~/.config/hypr/scripts/mac-clipboard.sh cut"))

-- macOS-style screenshots (grim + slurp). Ctrl variant = clipboard vs. file.
--   Cmd+Shift+3 / +4 / +5      -> full / region / window  to file
--   Cmd+Ctrl+Shift+3 / +4 / +5 -> same, to clipboard
for key, mode in pairs({ ["3"] = "full", ["4"] = "region", ["5"] = "window" }) do
    hl.bind(meta .. " + SHIFT + " .. key,
        hl.dsp.exec_cmd("~/.config/hypr/scripts/screenshot.sh " .. mode .. " file"))
    hl.bind(navMod .. " + SHIFT + " .. key,
        hl.dsp.exec_cmd("~/.config/hypr/scripts/screenshot.sh " .. mode .. " clipboard"))
end

-- Annotate a region in satty (markup, then save + copy)
hl.bind(meta .. " + SHIFT + 6", hl.dsp.exec_cmd("~/.config/hypr/scripts/screenshot.sh region annotate"))

-- Media keys, routed through swayosd-client so they show an on-screen display.
-- No brightness binds: this box has no backlight device (external DP monitor),
-- so brightnessctl would be a no-op. ddcutil would be the route if wanted.
local osd = "swayosd-client "
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd(osd .. "--output-volume raise"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd(osd .. "--output-volume lower"), { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd(osd .. "--output-volume mute-toggle"), { locked = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd(osd .. "--input-volume mute-toggle"), { locked = true })

-- Precise 1% steps with ALT held
hl.bind("ALT + XF86AudioRaiseVolume", hl.dsp.exec_cmd(osd .. "--output-volume +1"), { locked = true, repeating = true })
hl.bind("ALT + XF86AudioLowerVolume", hl.dsp.exec_cmd(osd .. "--output-volume -1"), { locked = true, repeating = true })

-- Requires playerctl
hl.bind("XF86AudioNext", hl.dsp.exec_cmd(osd .. "--playerctl next"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd(osd .. "--playerctl prev"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd(osd .. "--playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd(osd .. "--playerctl play-pause"), { locked = true })

-- Launch apps
hl.bind(launchMod .. " + F", hl.dsp.exec_cmd("firefox"))
hl.bind(launchMod .. " + G", hl.dsp.exec_cmd("chat-gpt"))

-- Move focus / swap window (vim keys)
local directions = { h = "left", l = "right", k = "up", j = "down" }
for key, dir in pairs(directions) do
    hl.bind(navMod .. " + " .. key, hl.dsp.focus({ direction = dir }))
    hl.bind(moveMod .. " + " .. key, hl.dsp.window.swap({ direction = dir }))
end

-- Switch workspaces / move active window to a workspace
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(navMod .. " + " .. key, hl.dsp.focus({ workspace = i }))
    hl.bind(moveMod .. " + " .. key, hl.dsp.window.move({ workspace = i }))
end

-- Relative workspace switching
hl.bind(navMod .. " + left", hl.dsp.focus({ workspace = "e-1" }))
hl.bind(navMod .. " + right", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(meta .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(meta .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with ALT + LMB/RMB and dragging
hl.bind("ALT + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind("ALT + mouse:273", hl.dsp.window.resize(), { mouse = true })


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- Blur behind the volume/media OSD so it lifts off the wallpaper (macOS-style).
-- ignore_alpha skips blurring the fully transparent area outside the pill, so
-- only the panel itself is frosted.
hl.layer_rule({
    name  = "blur-swayosd",
    match = { namespace = "^swayosd$" },
    blur = true,
    ignore_alpha = 0.2,
})

hl.window_rule({
    name  = "no-border-when-floating",
    match = { float = true },
    border_size = 0,
})

for _, class in ipairs({ "^(1Password)$", "^(Tandem)$", "^(Rofi|rofi)$", "^(Volume Control)$", "^(kitty-float)$" }) do
    hl.window_rule({
        name  = "float-" .. class,
        match = { class = class },
        float = true,
    })
end

hl.window_rule({
    name  = "rofi-stay-focused",
    match = { class = "^(Rofi|rofi)$" },
    stay_focused = true,
})

hl.window_rule({
    -- Ignore maximize requests from all apps. You'll probably like this.
    name  = "suppress-maximize-events",
    match = { class = ".*" },
    suppress_event = "maximize",
})
